### ISSUE TITLE
Rename package crawlercommons.url

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#107]
That code is specific to domains. I find the name 'crawlercommons.url' quite vague, especially if we add support for URL filtering elsewhere. What about renaming it to 'crawlercommons.domains' ?

**Comment by jnioche** [comment]
@crawler-commons/owners any thoughts?

**Comment by kkrugler** [comment]
+1 from me.

**Comment by lewismc** [comment]
+1

On Wednesday, December 2, 2015, Ken Krugler <notifications@github.com>
wrote:

> +1 from me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crawler-commons/crawler-commons/issues/107#issuecomment-161327252>
> .
>


-- 
*Lewis*
