### ISSUE TITLE
Detect gzip content via magic numbers

### ISSUE THREAD

**Issue by srwilson** [crawler-commons/crawler-commons#111]
There seem to be sites that return gzip content for sitemap files but do not set the gzip content type.  For example

```
curl -v 'http://spiderbites.nytimes.com/sitemaps/cooking.nytimes.com/sitemap.xml.gz' | zcat

< HTTP/1.1 200 OK
< Server: nginx/1.4.1
< Date: Wed, 16 Dec 2015 22:25:26 GMT
< Content-Length: 4599
< Connection: keep-alive
< x-amz-id-2: Y8v7HH8StinL+b0j3MjJ4snJk8n9HNieCXcy4firRKFzC3JYFqJxemO3y8prBs38wxtlKyN6TeU=
< x-amz-request-id: B0138BA0C59A6E3B
< Last-Modified: Wed, 16 Dec 2015 22:00:21 GMT
< ETag: "ba8d33493aaa55f3db93f54ae1417ae2"
< Accept-Ranges: bytes

<?xml version="1.0"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
...
```

The content is actually gzipped though.  In the parseSiteMap method it can it can check for the magic numbers that signify gzip content and then assume application/gzip.  Here's the snippet to do the detection.

```java
if (data.length > 2 && (data[0] == (byte)0x1f) && (data[1] == (byte)0x8b)) {
            contentType = "application/gzip";
}
```

**Comment by jnioche** [comment]
You don't need to implement the detection yourself. We have a [parseSiteMap](https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/sitemaps/SiteMapParser.java#L137)  method that does the content detection with Tika. It should detect that the content is zipped

**Comment by srwilson** [comment]
So the recommended way to call is the (byte[], url) method and not pass the content type from the fetched headers?  In other words does Tika detection work well enough to make the header content type unnecessary?  If so a bit of documentation might be helpful for new users.

**Comment by kkrugler** [comment]
Hi Scott - I've updated the JavaDocs to (hopefully) clarify that it's better to use the method that doesn't take an explicit contentType.
