### ISSUE TITLE
Why is everything in fetcher deprecated?

### ISSUE THREAD

**Issue by ThePixelPony** [crawler-commons/crawler-commons#113]
What do we use instead?

**Comment by Chaiavi** [comment]
Support for fetching is deprecated in CrawlerCommons and will be removed
eventually.

You can still use our fetcher with a release of CC which supports fetching,
or try a fetcher from an other 3rd party


Maybe use the apache httpComponents or something else.


Sorry
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kkrugler** [comment]
See discussion about this as part of issue #92.

Also it's better if you can use the mailing list at https://groups.google.com/forum/?fromgroups#!forum/crawler-commons for questions (like this one), versus filing an issue.

**Comment by ThePixelPony** [comment]
Oh, I see, thanks. Apologies. I'll use the mailing list if there's a next time.
