### ISSUE TITLE
Parsing of dates slow for Sitemaps

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#117]
The parsing of dates in [AbstractSiteMap.java](https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/sitemaps/AbstractSiteMap.java#L154) takes around 50% of the processing time of Sitemaps. 

This is due to a call to `DatatypeConverter.parseDateTime(date).getTime()`, there must be faster ways of parsing.

**Comment by kkrugler** [comment]
Hi Julien - for context, how significant is the overall time spent parsing sitemaps?

**Comment by jnioche** [comment]
Hi Ken, 

The parsing takes between 1 and 2.5 secs depending on the docs, see my edited comment on #116

**Comment by jnioche** [comment]
I tried a simple optimization on the SAX branch where we first try to parse with 

```java
SimpleDateFormat result = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX", Locale.getDefault());
```
then if it fails revert with the existing parser.

```
http://www.foxnews.com/sitemap.xml?idx=26 parsed in 1690 [3224 bytes per msec]
http://push.abs-cbn.com/sitemap/2015/ parsed in 511[4254 bytes per msec]
https://www.novinky.cz/sitemap/sitemap_articles_5.xml parsed in 1356[7228 bytes per msec]

http://www.foxnews.com/sitemap.xml?idx=26 parsed in 1396[3903 bytes per msec]
http://push.abs-cbn.com/sitemap/2015/ parsed in 431[5044 bytes per msec]
https://www.novinky.cz/sitemap/sitemap_articles_5.xml parsed in 1427[6869 bytes per msec]

http://www.foxnews.com/sitemap.xml?idx=26 parsed in 1721[3166 bytes per msec]
http://push.abs-cbn.com/sitemap/2015/ parsed in 514[4229 bytes per msec]
https://www.novinky.cz/sitemap/sitemap_articles_5.xml parsed in 1403[6986 bytes per msec]
```

The improvement is spectacular on doc 2 (takes less than half the time), slower on doc 3  possibly because the values don't match the pattern (need to trim the values?).

Just a starting point but I think it is definitely worth exploring.
