### ISSUE TITLE
SimpleRobotRules Serialization Problem

### ISSUE THREAD

**Issue by jmveramaiquez** [crawler-commons/crawler-commons#118]
The SimpleRobotRules class has a serialization problem due to the RobotRule inner class.
High performance serializers like Protostuff or Protobuffer, can not resolve due to the this$0 internal references in the inner classes to their parent class.

What they recommends on this case is to create the inner class as static, or avoid the use by defining the nested class at the same level of the parent.

Thanks!

**Comment by Chaiavi** [comment]
Thank you.

Can you address this issue and offer a pull request ?

**Comment by jmveramaiquez** [comment]
Of course,

	Josep Miquel

**Comment by jmveramaiquez** [comment]
The pull request is done and has passed all checks.
Is ready to be merged.

**Comment by jnioche** [comment]
Merged in #119
