### ISSUE TITLE
[Sitemaps] Update to the Sitemap official guidelines (50mb sitemap files)

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#132]
An update has been issued allowing sitemaps to consist of 50mb instead of 10mb file size:
http://blogs.bing.com/webmaster/November-2016/Increasing-the-size-limit-of-Sitemaps-file-to-addr

The fix should be put into the SiteMapParser:
https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/sitemaps/SiteMapParser.java

Where the line
public static final int MAX_BYTES_ALLOWED = 10485760;

Should be replaced with
public static final int MAX_BYTES_ALLOWED = 52428800;

I think that is the only fix, but I didn't check it thoroughly.

**Comment by sebastian-nagel** [comment]
Confirmed, also the "official" spec has been changed to 50 MB as size limit, cf. [[1](https://www.sitemaps.org/protocol.html#index)], [[2](https://www.sitemaps.org/faq.html#faq_sitemap_size)].
