### ISSUE TITLE
Incorrect crawl-delay value when robots content does not contain crawl-delay

### ISSUE THREAD

**Issue by guadenine** [crawler-commons/crawler-commons#139]
The SimpleRobotRulesParser implementation produces an invalid crawl delay value (-9223372036854775808) when crawl-delay is not set.
```
SimpleRobotRulesParser parser = new SimpleRobotRulesParser();
BaseRobotRules rules = parser.parseContent("http://domain.com", "".getBytes(), "text/plain", "Mozilla/5.0");
System.out.println("Crawl Delay: " + rules.getCrawlDelay());
```
Result: -9223372036854775808
Expected: -1

**Comment by kkrugler** [comment]
The value being returned is UNSET_CRAWL_DELAY from BaseRobotRules, which is Long.MIN_VALUE. Thus I don't think this is a bug.

If there's documentation somewhere that refers to -1, we should fix that.

**Comment by lewismc** [comment]
@guadenine do you have any source for the value being -1?

**Comment by guadenine** [comment]
No, I dont have the source, im now aware that it returns Long.MIN_VALUE, but I dont see the reasoning for it. The naturally expected return value of a missing crawl-delay is -1.
