### ISSUE TITLE
[Sitemaps] gzipped text files fail to parse

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#143]
SiteMapParser fails with
```
Exception in thread "main" crawlercommons.sitemaps.UnknownFormatException: Error parsing XML for: http://fihh.de/urllist.txt.gz
```
if an gzip compressed text sitemap is parsed (e.g., http://fihh.de/urllist.txt.gz). The [sitemaps spec](https://www.sitemaps.org/protocol.html#otherformats) explicitely allows that "you may compress your Sitemap text file using gzip".

**Comment by jnioche** [comment]
Just came across this issue when trying to parse "http://www.gstatic.com/s2/sitemaps/sitemap-00007-of-50000.gz"
