### ISSUE TITLE
[Sitemaps] SAX parser to stop URL at closing </loc>

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#153]
The sitemaps SAX parser does not stop a URL at the closing `</loc>`. If there is no closing `</url>` the URL contains all concatenated text, including line breaks. 

Attached [two documents](https://github.com/crawler-commons/crawler-commons/files/824399/sitemaps-invalid-sax-parser.zip) to reproduce the problem. Since both do not validate against the [sitemap schema](http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd)), the behavior of the DOM parser is acceptable (fails resp. adds only a single URL).

Note: the solution should not break #29 (no `<loc>` element at all).

**Comment by kkrugler** [comment]
It's always an interesting question whether it's a bug or not when parsing code doesn't handle a broken document :)

**Comment by sebastian-nagel** [comment]
Yes, but the SAX parser **does** handle it (for one of the two documents only if set to accept partial documents). It concatenates URLs to one long URL (which it better shouldn't).

**Comment by kkrugler** [comment]
By "handle" I meant "generate usable results". This comes up often on Tika with HTML parsing, where there's some badly broken file that a browser can render properly, but we don't extract the expected title (as an example). So is that a bug or an enhancement?

In any case, I've usually had to deal with this by keeping around more state, and catching cases of unclosed tags in a subsequent tag start where that tag shouldn't ever be inside of the enclosing tag.

**Comment by sebastian-nagel** [comment]
Ok, let's not dispute about the label.

**Comment by sebastian-nagel** [comment]
Wrapped some more sitemaps which are affected, see [warc.gz](https://commoncrawl-seeds.s3.amazonaws.com/sitemaps/test/sitemap-test-2017-03-24-long-runners.warc.gz). By concatenating all <loc> content sitemap parser emits URLs up to 8 MB length.

**Comment by sebastian-nagel** [comment]
To avoid unnecessary overhead the handler should not assume a forgotten close tag if a opening `<loc>` (or `<url>) was preceded by content (and not white space only). Otherwise in the normal case
```
...
</url>
<url>
  <loc>http://...</loc>
....
```
the method `maybeAddSiteMapUrl()` is called to times more with some white space, raising a MalformedURLException. This has obviously a lot of overhead, running the [sitemap performance test](https://groups.google.com/d/topic/crawler-commons/pOLsCVwRsxY/discussion) is up to 40% slower.

**Comment by jnioche** [comment]
good catch, thanks @sebastian-nagel
