### ISSUE TITLE
Decouple SiteMapParser from DOM processing

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#156]
The DOM Parsing is done within the SitemapParser class, we should externalise that to a separate class to simplify the switch between SAX and DOM processing and have a more logical organisation of the code whereby the logic used for the parsing is a separate detail from what SitemapParser provides as a  front end.

WDYT?

**Comment by sebastian-nagel** [comment]
Originally, the SAX parser (#116) was thought as a replacement of the DOM parser. If we decide to maintain both implementations in parallel: yes, the code needs to be re-factored, e.g.,
- SiteMapParser should become an abstract class hosting shared code
- DOM and SAX parser extend from it, but may provide own methods, e.g., to access the DOM or to return URLs via an iterator while parsing (SAX only)
- ev. provide a factory to construct a SiteMapParser object at runtime based on configuration params or properties
Good question: do this without breaking the existing API? Only extending it? New entry point/class?

**Comment by jnioche** [comment]
Thanks for your comments @sebastian-nagel 

> SiteMapParser should become an abstract class hosting shared code
> DOM and SAX parser extend from it

Not really what I had in mind. The  SitemapParser class does not have to be abstract - it can be a facade and delegate the parsing to the DOM or SAX classes while dealing with the other aspects such as mimetype etc... Not much point having an abstract class if the plan is to have a single implementation for parsing. 

> DOM and SAX parser extend from it, but may provide own methods, e.g., to access the DOM or to return URLs via an iterator while parsing (SAX only)

which means casting. Our code for the sitemap parsing is full of that and it is not user-friendly IMHO

> ev. provide a factory to construct a SiteMapParser object at runtime based on configuration params or properties

The SiteMapParser would determine internally which implementation to use based on the params or properties. 

Nothing would change from a user point of view - but internally we'd have a clearer separation between the XML processing code and the rest. The benefits are not just while we have 2 implementations, I'd really want us to be SAX only ASAP.

**Comment by kkrugler** [comment]
There's some testing advantage (easier mocking for code that's using SiteMapParser) to having it be an abstract base class with one (or two, short term) concrete implementations.

Agree that having only SAX-based should happen sooner rather than later.

**Comment by jnioche** [comment]
Not a problem since the DOM parser has now been removed
