### ISSUE TITLE
url is excluded from the sitemap as it is not a valid url = not under the base url/sitemap

### ISSUE THREAD

**Issue by leccyril** [crawler-commons/crawler-commons#158]
i am parsing robots.txt to retrieve sitemapindex and then url in sitemap, when parsing i have those warn for each url in sitemap but it is normal url are note under http://.../sitemap and moreover sitemaps are in http://.../sitemap..xml it is a warn but what is the meaning ? 
thanks !

**Comment by leccyril** [comment]
for more precision i have 2 sitemaps into robots.txt one have url like http://.../sitemap_X.xml (it is ok) other is http://.../sitemap/sitemap_video.xml and talk about video

**Comment by sebastian-nagel** [comment]
Hi, could you add a snippet of your logs to see the exact warning? This will help to understand what the problem is. It's ok, if URLs are anonymized.

**Comment by leccyril** [comment]
for example 

http://www.marmiton.org/robots.txt there is 2 sitemaps when i parse the second sitemap i have the warning

`http://www.marmiton.org/wsitemap_index.xml
http://www.marmiton.org/wsitemap_video_index.xml
[main] WARN crawlercommons.sitemaps.SiteMapParser - URL: http://www.marmiton.org/video/video-youtube_crepes-au-chocolat_1468.aspx is excluded from the sitemap as it is not a valid url = not under the base url: http://www.marmiton.org/sitemap/

[main] WARN crawlercommons.sitemaps.SiteMapParser - URL: http://www.marmiton.org/video/video-youtube_bowl-cake-facon-brunch_1467.aspx is excluded from the sitemap as it is not a valid url = not under the base url: http://www.marmiton.org/sitemap/`

**Comment by sebastian-nagel** [comment]
The URL is excluded because it does not share the the same URL prefix with the sitemap location, see the [sitemap spec](https://www.sitemaps.org/protocol.html#location). Please, try to use
```
SiteMapParser parser = new SiteMapParser(false);
```
to get a non-[strict](http://crawler-commons.github.io/crawler-commons/0.7/crawlercommons/sitemaps/SiteMapParser.html#strict) parser which accepts URLs with different prefix. At present, no cross-submit is implement (#85).

**Comment by leccyril** [comment]
it seems to be ok great work... thanks!

i don't find any simple example to retrieve sitemap from your tool it is possible simply ? i use another lib and then when i have sitemap list i use it...  like this  i think with your tool you don't add url in disallow ? isn't it ? 

ore have i to as a new question ?

**Comment by sebastian-nagel** [comment]
> your tool you don't add url in disallow

This sounds like it's related to the [robots.txt parser](http://crawler-commons.github.io/crawler-commons/0.7/index.html?crawlercommons/robots/SimpleRobotRulesParser.html), the [SiteMapParser](http://crawler-commons.github.io/crawler-commons/0.7/crawlercommons/sitemaps/SiteMapParser.html) does not filter URLs by robots rules. That has to be implemented by the user. Please, read the API docs first, this should answer most of your questions. Thanks!

**Comment by leccyril** [comment]
`SimpleRobotRulesParser robotParser = new SimpleRobotRulesParser();
        SimpleRobotRules robotRules= (SimpleRobotRules)robotParser.parseContent("http://www.marmiton.org", IOUtils.toByteArray(new URL("http://www.marmiton.org/robots.txt").openStream()), "text/plain", "*");`

and then for each sitemap i retrieve all URL (the disallow is used only when i do not parse url from sitemap but when i crawl the website from the root url)

thank you !
