### ISSUE TITLE
RSS parser ignores pubDate of link

### ISSUE THREAD

**Issue by MichealKum** [crawler-commons/crawler-commons#166]
SiteMapParser.parseRSS uses pubDate of channel node as a lastMod for all items ignoring pubDate tag of item node.

**Comment by lewismc** [comment]
hi @MichealKum ... can you propose a patch? A Unit test would be ideal ;)

**Comment by MichealKum** [comment]
@lewismc sure

**Comment by MichealKum** [comment]
@lewismc something like this:
[ISSUE-166_0.patch.zip](https://github.com/crawler-commons/crawler-commons/files/1081967/ISSUE-166_0.patch.zip)

**Comment by lewismc** [comment]
Hi @MichealKum , sorry can you propose a pull request? Thank you

**Comment by MichealKum** [comment]
@lewismc I unable to push my branch to the repository. Maybe I do it wrong?

**Comment by MichealKum** [comment]
@lewismc sorry, now I know, how to do that. PR is created.

**Comment by lewismc** [comment]
Excellent, PR is available at https://github.com/crawler-commons/crawler-commons/pull/167. Thank you, I'll review when I get a minute.
