### ISSUE TITLE
Sitemap SAX parsing mangles target URLs

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#169]
http://stylecaster.com/sitemap.xml
gives 
http://stylecaster.com/sitemap.xml?yyyy=2017
where it should be 
http://stylecaster.com/sitemap.xml?yyyy=2017&mm=07&dd=11

the DOM parsers handles these correctly.

**Comment by sebastian-nagel** [comment]
Confirmed. Is anyone working on it? Otherwise I'll start.

**Comment by jnioche** [comment]
Am not, thanks @sebastian-nagel

**Comment by sebastian-nagel** [comment]
PR tested in CC July crawl. I'm going to commit during the next days if there are no objections. Thanks!
