### ISSUE TITLE
Incorrect domains returned by EffectiveTldFinder

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#172]
The method `EffectiveTldFinder.getAssignedDomain(hostname)` returns an incorrect domain in a couple of cases. This was detected by a comparison with the Python module [tldextract](https://pypi.python.org/pypi/tldextract) which is also based on the [public suffix list](https://publicsuffix.org/).

1. exceptions to wildcard rules are not recognized as valid domain, e.g. with the rules
   ```
   *.kawasaki.jp
   !city.kawasaki.jp
   ```
   the domain for "www.city.kawasaki.jp" should be "city.kawasaki.jp".

2. the domain detection fails entirely of the .za top-level domain: "blogs.uct.ac.za" should give "ac.za". A test whether the last element "za" is a valid TLD fails but the [.za registrar](https://www.zadna.org.za/content/page/domain-information/) does not allow .za alone as TLD.

3. detection fails for internationalized domain names in their punycoded (ASCII) form: for "спб.бесплатныеобъявления.рф" the domain "бесплатныеобъявления.рф" is correctly returned but not for the punycode equivalent "xn--90a1af.xn--80abbembcyvesfij3at4loa4ff.xn--p1ai". The public suffix list contains the utf-8 representation of IDNs and must be (additionally) transposed to the ASCII/Punycode form.

**Comment by jnioche** [comment]
@sebastian-nagel what about merging what you've already done as part of 0.9 and opening a new issue for the stuff you haven't yet done?

**Comment by sebastian-nagel** [comment]
Ok, from my side. I'll get on this back soon (need it in about two weeks). Depends on when to release 0.9. I can try to get it done the next days. Right now, there are multiple tests commented out or just only logging failures without actually failing.

**Comment by jnioche** [comment]
We could release 0.9 as soon as you've merged these changes: this is the only issue flagged for 0.9 and we already have a few things there (e.g. namespaces) that would be worth releasing ASAP

**Comment by sebastian-nagel** [comment]
Let me work on it today. Merging fails and I'll try to get a PR ready today evening.

**Comment by sebastian-nagel** [comment]
Done, except for IDNs which do not get processed. The puny-coded form however works. I'll open a separate issue for this, requires more changes, esp. to handle mixed usage of IDN and punycoded parts.
