### ISSUE TITLE
Remove DOM-based sitemap parser?

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#177]
@sebastian-nagel do you have any benchmarks between the SAX and DOM parsers?

if there are no cases missed by the SAX parser, then shall we remove the DOM one?

@crawler-commons/committers

**Comment by sebastian-nagel** [comment]
We have an open PR #162 to support sitemap extensions (news, videos, etc.) which applies only to the DOM parser. But I can run a benchmark and comparison again after #176 is reviewed and committed.

**Comment by jnioche** [comment]
> I can run a benchmark and comparison again after #176 is reviewed and committed.

#176 is now merged in the main branch. Would be great if you had time to do the above.

Re-#162, I'd be in favour of implementing it on SAX in a more generic way, see https://github.com/crawler-commons/crawler-commons/pull/162#issuecomment-299467740 but that's a different topic

**Comment by sebastian-nagel** [comment]
Checked DOM and SAX parser after #176: SAX is faster and more robust / extracts more URLs (also with strictNamespace).

**Comment by jnioche** [comment]
Have opened a PR for removing the DOM parser in case the vote on the mailing list goes in that direction.
