### ISSUE TITLE
sitemap parser assumes wrong baseUrl

### ISSUE THREAD

**Issue by jjYBdx4IL** [crawler-commons/crawler-commons#182]
It refuses to accept the links from the archive.org sitemaps:

20:36:12,023 WARN  [crawlercommons.sitemaps.SiteMapParser] (IdxTask) URL: https://archive.org/details/ARCHIVEIT-3490-TWELVE_HOURS-FHIFEO-00000 is excluded from the sitemap as it is not a valid url = not under the base url: https://archive.org/sitemap/

The base url should probably be https://archive.org/ and not restrict to sub-paths.

**Comment by kkrugler** [comment]
As per https://www.sitemaps.org/protocol.html#location, the sitemap parser is doing the right thing here - archive.org has their sitemap file in the wrong location.

Note that if you create the SiteMapParser with strict = false, then these URLs will be allowed.

**Comment by sebastian-nagel** [comment]
Relates to #85, the sitemap is announced in http://archive.org/robots.txt
