### ISSUE TITLE
Follow Redirects on Sitemap URLs?

### ISSUE THREAD

**Issue by JoeJErnst** [crawler-commons/crawler-commons#191]
I have a robots.txt file that gives me the URL of a sitemap in plain http, but that URL redirects to https using a 301.  This is causing a SaxParseException in the SiteMapParser:

SiteMapParser SaxParseException: "Premature end of file"

Here is the relevant part of the stack trace:

`
Error parsing sitemap http://www.jamescorlewautomotive.com/sitemap.xml: Premature end of file.
crawlercommons.sitemaps.UnknownFormatException: Failed to parse http://www.jamescorlewautomotive.com/sitemap.xml
	at crawlercommons.sitemaps.SiteMapParser.processXml(SiteMapParser.java:430)
	at crawlercommons.sitemaps.SiteMapParser.processXml(SiteMapParser.java:285)
	at crawlercommons.sitemaps.SiteMapParser.parseSiteMap(SiteMapParser.java:236)
	at crawlercommons.sitemaps.SiteMapParser.parseSiteMap(SiteMapParser.java:208)
	at crawlercommons.sitemaps.SiteMapParser.parseSiteMap(SiteMapParser.java:158)
`

Is there a way to tell the parser to follow redirects?

I am using version 0.9, but I got the same error on 0.8.

**Comment by jnioche** [comment]
Sorry for the late reply, I've just found this issue. Handling the http code and redirections should not be the responsibility of the SitemapParser itself but should be done by whichever code is doing the fetching. I see that you are using [a method on the parser which takes a URL as argument](https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/sitemaps/SiteMapParser.java#L153) and does the fetching but this is there merely as a simplistic solution. If you want to handle redirections, do that outside the parser code. 
Will close this issue for now but feel free to reopen it if you want to discuss it further. Thanks!
