### ISSUE TITLE
SimpleRobotRulesParser: Expose MAX_CRAWL_DELAY

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#194]
SimpleRobotRulesParser keeps [MAX_CRAWL_DELAY](https://github.com/crawler-commons/crawler-commons/blob/crawler-commons-0.9/src/main/java/crawlercommons/robots/SimpleRobotRulesParser.java#L349) as private static variable. Shouldn't it be defined by the crawler which delay is acceptable? A black-box behavior does not really make sense, as well as a fixed invisible value of 300,000 seconds (two fetches per week).

**Comment by kkrugler** [comment]
Closed via commit 67adc27. Thanks @aecio!
