### ISSUE TITLE
[Robots.txt] Path analyse bug with url-decode if allow/disallow path contains escaped wild-card characters

### ISSUE THREAD

**Issue by tkalistratov** [crawler-commons/crawler-commons#195]
The problem is with url-decode:
https://github.com/crawler-commons/crawler-commons/blob/4b13456bc954f97ae209446b3736976b2a9ea298/src/main/java/crawlercommons/robots/SimpleRobotRulesParser.java#L631
Google robots.txt specification (https://developers.google.com/search/reference/robots_txt?hl=en) says:
"Non-7-bit ASCII characters in a path may be included as UTF-8 characters or as percent-escaped UTF-8 encoded characters per RFC 3986."
So for example, if we have rule ``Disallow: /*%2F*`` (blocks all rules with url-encoded urls in it), SimpleRobotRulesParser interprets it like ``Disallow: /*/*``, and this rule kills much more urls.

So, parser should url-decode not the whole path, but only url-encoded Non-7-bit ASCII characters in a path

**Comment by sebastian-nagel** [comment]
[RFC 9309](https://datatracker.ietf.org/doc/rfc9309/) is much clearer:

> Octets in the URI and robots.txt paths outside the range of the ASCII coded character set, and those in the reserved range defined by [RFC3986], MUST be percent-encoded as defined by [RFC3986] prior to comparison.
> 
> If a percent-encoded ASCII octet is encountered in the URI, it MUST be unencoded prior to comparison, unless it is a reserved character in the URI as defined by [RFC3986] or the character is outside the unreserved character range.
> 
> [...]
> 
> If crawlers match special characters verbatim in the URI, crawlers SHOULD use "%" encoding.  

There are also two examples there.

One note: many robots.txt files tend to specify paths which include characters with a potentially special meaning twice. One example from Wikipedia's robots.txt:
```
Disallow: /wiki/MediaWiki:Spam-blacklist
Disallow: /wiki/MediaWiki%3ASpam-blacklist
```
