### ISSUE TITLE
[Sitemaps] Support legacy namespaces

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#210]
After #173 the sitemap parser is aware of XML namespaces and can be configured to ignore all elements (including URLs from `<loc>` elements) which are not in the `http://www.sitemaps.org/schemas/sitemap/0.9` namespace. This allows to exclude image and video links which also use the `<loc>` element but in a different namespace. However, URLs/URIs used to identify the namespace are not always persistent which makes the namespace validation fail in the following cases:
- different schema/protocol `https` instead of `http`
- relative URLs: `//www.sitemaps.org/schemas/sitemap/0.9`
- trailing slash in URL
- old protocol versions: `http://www.google.com/schemas/sitemap/0.84`

See also the [discussion #173](/crawler-commons/crawler-commons/pull/173#discussion_r139123661). It should be possible to be (optionally) tolerant regarding variations in the namespace URI.

**Comment by jnioche** [comment]
implemented by #211
