### ISSUE TITLE
Release 0.10

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#212]
@crawler-commons/committers what about releasing 0.10 soon? There's a couple of open PRs: 
-  #211 which needs reviewing
-  #193  @sebastian-nagel is it on hold until we do #197?

It would be good to have a new release soon so that we get the benefits of the various recent improvements. We can always do a new release soon after if necessary.

**Comment by sebastian-nagel** [comment]
+1

#193 has been modified not to use Tika (just assumes text/plain for the tested robots.txt) - Yes, it adds another main() method but there are already multiple of them. We can move them all to a different module together with #197.

**Comment by kkrugler** [comment]
+1
