### ISSUE TITLE
[Sitemaps] Sitemap index: stop URL at closing </loc>

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#213]
(cf. [Nutch mailing list](https://lists.apache.org/thread.html/8ebcffbe2bd8edafb6030e4f28fceee07aee08a1ce06a94755ee8d74@%3Cuser.nutch.apache.org%3E)

With #153 the sitemaps SAX parser handles sitemaps with missing or not properly closed <url> elements. This should be also done for sitemap indexes, e.g.:
```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex>
<sitemap>
<loc>https://www.example.orgl/sitemap1.xml</loc>
<loc>https://www.example.org/sitemap2.xml</loc>
</sitemap>
</sitemapindex>
```

**Comment by sebastian-nagel** [comment]
Hi @kkrugler, the problem is that the value of both <loc> elements is concatenated (just verified that this is still the case).
![screenshot_20181212_183049](https://user-images.githubusercontent.com/1630582/49887282-3c6bf100-fe3c-11e8-96de-cb6cc9cbc6aa.png)

Of course, a correct sitemap index would have the <sitemap> element closed before the next <loc> element. But a forgiving parser should auto-close the <sitemap> as soon the next <loc> is seen. The handler for sitemaps (root element <urlset>) does an auto-close of the <url> element on a new <loc>.

Good catch regarding the mangled URL.

**Comment by sebastian-nagel** [comment]
After a closer look: the interface looks correct:
- every AbstractSiteMap has its own URL from where it can be retrieved
- a SiteMapIndex holds a list of SiteMaps (getter: SiteMapIndex.getSitemaps())
- each SiteMap a list of SiteMapURLs (getter: SiteMap.getSiteMapUrls())

It already reflects the recursion of sitemap indexes, as does the SiteMapParser.walkSiteMap(...) method.

**Comment by kkrugler** [comment]
What confuses me a bit is that based on http://sitemaps.org/protocol.php, I see the definition of a sitemap index as:

```
 * Begin with an opening `<sitemapindex>` tag and end with a closing `</sitemapindex>` tag.
 * Include a `<sitemap>` entry for each Sitemap as a parent XML tag.
 * Include a `<loc>` child entry for each `<sitemap>` parent tag.
```

So it's a _single_ location (URL) for each sitemap entry, versus a list of locations. Does that make sense?

**Comment by sebastian-nagel** [comment]
The sitemap index given above is invalid, it does not follow the spec. However, as the parser is designed to parse also invalid sitemaps it should be able to parse also invalid sitemap indexes and silently try to fix their structure by assuming `</sitemap><sitemap>` between the two `<loc>` elements. The SiteMapHandler class also auto-closes `<url>` elements. I'll open a PR to address it.
