### ISSUE TITLE
URLs with query params but no path don't match against rules

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#215]
A single `Disallow: /` statement in the robots.txt "tells the robot that it should not visit any pages on the site." [robots.txt spec](http://www.robotstxt.org/robotstxt.html). It should also apply to URLs with query only (without a path element):
```
% cat /tmp/robots.txt 
User-agent: *
Disallow: /
% java -cp ... crawlercommons.robots.SimpleRobotRulesParser file:/tmp/robots.txt '*' 'http://www.example.com?q=a'
Checking URLs:
allowed         http://www.example.com?q=a
```

**Comment by kkrugler** [comment]
Fixed via [bef1b84](https://github.com/crawler-commons/crawler-commons/commit/bef1b8437e63930bcbab82a3f754bf835cda5cca)
