### ISSUE TITLE
[Sitemaps] Trim Unicode whitespace around URLs

### ISSUE THREAD

**Issue by moviewang** [crawler-commons/crawler-commons#224]
![image](https://user-images.githubusercontent.com/7558849/49796909-ebdf8f80-fd78-11e8-9c73-a742439b8e20.png)

loc.toString().trim() didn' trim all whitespace

**Comment by sebastian-nagel** [comment]
Hi @moviewang, can you share a minimal sitemap to reproduce your problem? It's ok if the URLs are masked but the white space should be there. Thanks!
After a first look: [String.trim()](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#trim--) only removes ASCII white space and control characters and [does not remove all Unicode white space](https://bugs.openjdk.java.net/browse/JDK-8159029). I see no issues replacing the trim() by a method which also strips Unicode white space, similar [StringUtils.strip() from commons-lang](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#strip-java.lang.String-).

**Comment by moviewang** [comment]
> Hi @moviewang, can you share a minimal sitemap to reproduce your problem? It's ok if the URLs are masked but the white space should be there. Thanks!
> After a first look: [String.trim()](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#trim--) only removes ASCII white space and control characters and [does not remove all Unicode white space](https://bugs.openjdk.java.net/browse/JDK-8159029). I see no issues replacing the trim() by a method which also strips Unicode white space, similar [StringUtils.strip() from commons-lang](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#strip-java.lang.String-).

Yes, the sitemap's loc elements contains white space, but I'have no rights to modify it. Is there any else approach to solve the problem. Thanks!

**Comment by kkrugler** [comment]
Hi @moviewang - can you provide the URL to the sitemap?

**Comment by moviewang** [comment]
![image](https://user-images.githubusercontent.com/7558849/49847181-c9e21d80-fe09-11e8-9769-51ed30b01815.png)
Hi@kkrugler - The sitemapIndex content like this.

**Comment by kkrugler** [comment]
@moviewang - the dates in your example aren't valid for sitemaps, then need to follow [one of these](https://www.w3.org/TR/NOTE-datetime) formats. So if the dates are in UTC, they should be something like `2018-12-12T02:36:56Z`.

There are two other issues, which I'll file as bugs separately, but only one might impact you. Data strings aren't getting trimmed, so the whitespace around the date string could cause problems.

**Comment by moviewang** [comment]
Hi @sebastian-nagel @kkrugler 
Thanks a lot ,I'm very grateful to you for your help. the problem maybe caused by the the url contains  unicode white space as @sebastian-nagel said. Please close this issue. Thanks!!!

**Comment by sebastian-nagel** [comment]
Hi @moviewang, I would suggest the parser also trim Unicode white space. I'll open a PR to fix this. The intention of my inquiry was to make sure whether this is the reason for your problem. Thanks!
