### ISSUE TITLE
XMLIndexHandler needs to accumulate the lastmod date string before parsing

### ISSUE THREAD

**Issue by kkrugler** [crawler-commons/crawler-commons#225]
Currently the code in `XMLIndexHandler.characters()` just tries to parse whatever it's passed as a date. But this handler can (and will) be passed text incrementally, so it needs to be accumulated, and in the `endElement()` method it can then (a) trim the string, and (b) try to parse the date.

You can see this behavior if you use a `<![CDATA[xxx]]>` format for the `<lastmod>` data, where `characters()` is called with some spaces and a newline, before getting called with the actual string.

**Comment by sebastian-nagel** [comment]
Actually, this should be fixed in advance for all elements with text content (<priority> and <changefreq>). Should also check the handlers for feeds and sitemap extensions.

**Comment by kkrugler** [comment]
The XMLIndexHandler does append characters for `<loc>` elements, just not the `<lastmod>` element. The `XMLHandler` has more issues in `characters()`, as it doesn't append for `<changefreq>`, `<lastmod>` or `<priority>`. I'll open a new issue for that.
