### ISSUE TITLE
error whit sitemap tar.gz

### ISSUE THREAD

**Issue by leccyril** [crawler-commons/crawler-commons#229]
hello, 

we have a problem when a sitemap is compressed for example 👍 

https://www.amazon.fr/sitemaps.2307ea63773dfee.SitemapIndex_0.xml.gz

lot of websites used this type of sitemap it will cause an issue, there is no possibility to untar to xml if it is zipped ? 

`// retrieve all disallow, then all sitemaps
			SimpleRobotRules robotRules = (SimpleRobotRules) robotParser.parseContent(website.url,
					IOUtils.toByteArray(robotsTxtStream), "text/plain", configuration.getString(AGENT_NAME));
`

then when i do getSItemaps and open connection it will cause error

**Comment by sebastian-nagel** [comment]
Hi @leccyril, I'm not able to fetch the sitemap. The server responded with HTTP status 500 (Internal Server Error) in the first trial, resp. a 404 (Not Found) in further trials. In case the sitemap failed to parse, please, attach the file to this issue. Thanks!

**Comment by sebastian-nagel** [comment]
Closing. If a URL fails to be fetched it will cause an IOException which must be handled by the calling code. Gzipped sitemaps are handled properly by SiteMapParser.
