### ISSUE TITLE
Release 0.11 ?

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#236]
@crawler-commons/committers, shall we release 0.11 after merging #235 (address #219)?

**Comment by jnioche** [comment]
Have merged #235
+1 to release 0.11

**Comment by kkrugler** [comment]
+1 to a release.

What about calling this 1.0? I don't think there's any major functionality that's missing from the original goal, yes?

And other than #197 I don't see any major architectural changes being proposed.

**Comment by sebastian-nagel** [comment]
+1  With support for video/image/etc. extensions the sitemap parser can now be called complete and #197 will not change the API.

**Comment by jnioche** [comment]
will do the release over the week-end

**Comment by kkrugler** [comment]
@jnioche thanks!

**Comment by sebastian-nagel** [comment]
We've released 1.0 instead.
