### ISSUE TITLE
Usage of SiteMapParser

### ISSUE THREAD

**Issue by pr3mar** [crawler-commons/crawler-commons#237]
Hi,

this might be a silly question, but still.

I noticed that `SiteMapParser.parseSiteMap()` returns `AbstractSiteMap`, can you give me some examples of how this is intended to be used?

Thanks!

**Comment by sebastian-nagel** [comment]
Actually, an instance of SiteMap or SiteMapIndex is returned. You need to check which one to decide how to proceed. Two examples: [Nutch's SitemapProcessor](https://github.com/apache/nutch/blob/ac02d82/src/java/org/apache/nutch/util/SitemapProcessor.java#L226) and [StormCrawler's SiteMapParserBolt](https://github.com/DigitalPebble/storm-crawler/blob/3b7b3b4/core/src/main/java/com/digitalpebble/stormcrawler/bolt/SiteMapParserBolt.java#L192).

**Comment by pr3mar** [comment]
This is great @sebastian-nagel! 
Thank you for the quick reply
