### ISSUE TITLE
[Sitemaps] Unit tests depend on system timezone

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#238]
Detected by @kkrugler, see [discussion in CC forum](https://groups.google.com/d/msg/crawler-commons/6q2iy9G8-Zg/GlppBwTwBgAJ).

The unit test `testDateParsing()` in `AbstractSiteMapTest` fails if the system timezone has a negative offset. The date format used in the unit test uses the system timezone which makes turns the date string into a date one day earlier.

The issue is originally caused by #217 which replaced the javax.xml.bind.DatatypeConverter used to parse short dates ("2017-03-27") by a custom date parser which assumes dates in UTC while DatatypeConverter has used the local time zone.  The [W3C Datetime format](https://www.w3.org/TR/NOTE-datetime) referenced in the [sitemaps protocol spec](https://www.sitemaps.org/protocol.html#xmlTagDefinitions) does not
mention anything about the time zone if the date does not contain one.

There are two solutions:
1. restore the old behavior (until 0.9) where dates without time zone depend on the system timezone. This will make the parser return different date times when running in different time zones.
2. fix the date format used in the unit test

Comments are welcome!

**Comment by sebastian-nagel** [comment]
PR open to fix the date format used in the unit test.  But I can also provide a PR for solution 1 if desired.

**Comment by jnioche** [comment]
I think it makes more sense to assume that the time is UTC if no zone is specified in the date, will merge your PR shortly

**Comment by kkrugler** [comment]
That was fast - thanks @sebastian-nagel!
