### ISSUE TITLE
Robots parser to always handle absolute sitemap URL even without valid base URL

### ISSUE THREAD

**Issue by pr3mar** [crawler-commons/crawler-commons#240]
I get an `Invalid URL with sitemap directive` for a sitemap url which is not relative.

I noticed in the implementation [here](https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/robots/SimpleRobotRulesParser.java#L740) that it only handles relative URLs, which might not be the case always, as now it is preferred to have the absolute URL for the sitemap in `robots.txt`.

Therefore if there is a URL provided with the sitemap, we cannot access it.

**Comment by sebastian-nagel** [comment]
Hi @pr3mar,
the implementation is ok, see the API doc of [URL(URL context, String spec)](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#URL-java.net.URL-java.lang.String-) - it allows that spec is an absolute URL. You can verify that absolute paths are accepted, e.g., by parsing one of the robots.txt files in the test resources:
```
% cat src/test/resources/robots/www.flot.com-robots.txt
...
Sitemap: http://flot.com/sitemap_index.xml

% java -cp ... crawlercommons.robots.SimpleRobotRulesParser file:$PWD/src/test/resources/robots/www.flot.com-robots.txt
...
 - number of sitemap URLs: 1
   sitemaps[0]: http://flot.com/sitemap_index.xml
```

Can you share the robots.txt file which causes the problem?

**Comment by pr3mar** [comment]
Seems like it was an invalid `robots.txt`, I was getting it for an entire evening, but not since they updated it. I will post it (if) I encounter it again.
Thanks for the explanation, and incredibly fast response, you are amazing!

**Comment by pr3mar** [comment]
Actually, here it is:

```
User-Agent: *
Allow: /
Disallow: /fileadmin/global/
Disallow: /t3lib/
Disallow: /nc/
Disallow: *no_cache*
Disallow: /*cHash
Disallow: /typo3/
Disallow: /urednik/
Disallow: /typo3conf/
Disallow: /typo3temp/
Disallow: /*?id=*
Disallow: /*&type=98
Disallow: /*&type=100

Sitemap: http://www.e-prostor.gov.si/?eID=dd_googlesitemap
```

**Comment by kkrugler** [comment]
I took a look at http://www.e-prostor.gov.si/robots.txt, and noticed that it's got problems with line endings: the first entry or so is correctly terminated by CRLF, but after that it several with just CR (0x0d) values. Though we should handle that correctly, and when I downloaded that file and added it as a test case, it worked.

**Comment by kkrugler** [comment]
@pr3mar - can you provide **exactly** the code you're using to parse the robots.txt file?

**Comment by pr3mar** [comment]
This is the definition:

```scala
  private val robotRules: SimpleRobotRules = robotsRulesParser.parseContent(site.domain.get, site.robotsContent.get.getBytes, contentType, robotNames)
```
I use contentType = "text/plain", and robotNames = "*"
I get the content (`site.robotsContent.get.getBytes`) via htmlUnit, but at first I get it as `String`, and then convert it into `Array[Bytes]`, to reuse the method

**Comment by sebastian-nagel** [comment]
@pr3mar, what does `site.domain.get` return? The first argument passed to `parseContent(...)` should be the URL of the robots.txt. It must be a complete and valid URL string, not a domain name. But we should relax the parser so that it returns the sitemap URL if it's a absolute URL also in case the base URL is invalid.

**Comment by pr3mar** [comment]
@sebastian-nagel it's the absolute bare minimum of the domain, without `www`, in this example it is `e-prostor.gov.si`
So, in order to fix it I need to get the canonical version of it, directly to the `robots.txt` file, right, i.e. `http://www.e-prostor.gov.si/robots.txt`

**Comment by sebastian-nagel** [comment]
Yes, you need the complete robots.txt URL. We'll fix the parser so that it returns an valid and absolute sitemap URL also if the base URL isn't valid. We should also improve the Javadoc.

**Comment by sebastian-nagel** [comment]
Thanks, @pr3mar! Now absolute sitemap URLs should be kept even if the robots.txt URL is invalid.

**Comment by pr3mar** [comment]
Happy to be of service, you helped me a lot to build my own parser!
I'd be honoured  if you took a look at it,  it's [here](https://github.com/pr3mar/ieps-crawler).

**Comment by sebastian-nagel** [comment]
Nice project! And another one in the long list of [crawler](https://github.com/topics/crawler)/[web-crawler](https://github.com/topics/web-crawler)/[spider](https://github.com/topics/spider) projects.
