### ISSUE TITLE
[BasicNormalizer] sorting the Query Parameters

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#246]
When normalizing a URL should these two urls be normalized to the same url ?
http://shekhargulati.com?lang=en&article=fred
http://shekhargulati.com?article=fred&lang=en

This can be achieved by sorting the query params.

The above example was taken from [UrlCleaner](https://github.com/shekhargulati/urlcleaner/blob/master/src/test/java/com/shekhargulati/urlcleaner/UrlCleanerSpec.java)

It is an actual unit test there (one which we fail :-(   ), the test name is: shouldSortQueryParameters

**Comment by kkrugler** [comment]
We sort query parameters when normalizing (in other projects), so yes, I think that's true.
