### ISSUE TITLE
Normalizing WWW to the naked domain

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#257]
Our BasicNormalizer should normalize the "www" subdomain as there are many sites which can be accessed using the www subdomain as well as the naked domain.

[Wikipedia, URL Normalization](https://en.wikipedia.org/wiki/URL_normalization)
Search the page for: "Removing or adding “www” as the first domain label"

**Comment by sebastian-nagel** [comment]
Of course, this is a frequent reason for duplicates. However,
- not *all* sites can be accessed with leading "www." stripped
- many sites choose a domain name including "www." as canonical name and redirect you to avoid duplicates. Here a crawler must not strip the "www." or it sees only redirects. It can be only an optional operation.
- stripping must be done carefully, e.g. "www.com" is a valid registered domain

**Comment by Chaiavi** [comment]
Yes, I see there are many pitfalls here.

The Wikipedia suggestions:

How can this be done safely?
The intuitive option I see here is to resolve both urls (with and without www) and see if they go to the same page, but this seems a very costly operation for a normalizer.

Another option is to hold an internal DB (may be just an internal list) with all normalized urls (as the normalizer should be some sort of static singleton), and check if that url alredy was normalized with WWW or without WWW and normalize them in the same way

How would you suggest implementing this feature ?

**Comment by sebastian-nagel** [comment]
The interface of URLFilter resp. BasicURLNormalizer is really basic - URL string in, URL string or null out. I would avoid implementing any overtly complex heuristics and in any case not to introduce site effects which may threaten performance (need to run safely on 100 millions of URLs). Make the stripping of "www." optional and/or move it to a new class (eg. AggressiveURLNormalizer, HomePageNormalizer) which does this and other potentially destructive normalizations, eg. removing the director index (index.html).

**Comment by Chaiavi** [comment]
Even if aggresiveURLNormalizer is created, I still don't understand how it can be done.

Just stripping the www part (even optionally) seems like a bad practice as the URL might now be broken because maybe there is no page without www

How should one implement this part of normalization?

**Comment by kkrugler** [comment]
The way we've handled potentially bad normalization is by auto re-trying during the fetch process, if you get back a 404 where the domain might have had this normalization applied. E.g. in our crawler we assume that if there's a sub-domain, we wouldn't have normalized away the 'www' part, so we only retry if we get a 404 and the domain name == PLD.

**Comment by kkrugler** [comment]
I'm going to close this issue. I'd suggest opening another issue to implement a new, more aggressive/sophisticated normalizer as per @sebastian-nagel's suggestion above. There's a lot that could be done, e.g. sorting query parameters, support for stripping common session and ad-tracking parameters, getting rid of query parameters with really long values, etc. which could be part of more sophisticated normalization.
