### ISSUE TITLE
can't parse sitemap 

### ISSUE THREAD

**Issue by saiprashanth24** [crawler-commons/crawler-commons#258]
hi ,
i am unable to parse and extract urls for the sitemap file 
https://help.zoho.com/portal/sitemaps/sitemap-Articles-4001524317312.xml

` SiteMapParser smp = new SiteMapParser();
        URL onlineSitemapUrl = new URL("https://help.zoho.com/portal/sitemaps/sitemap-Articles-4001524317312.xml");
        SiteMap sitemap = new SiteMap();
        sitemap = (SiteMap) smp.parseSiteMap(IOUtils.toByteArray(onlineSitemapUrl), onlineSitemapUrl);
        ArrayList<String> urlsfromSitemap = new ArrayList();
        Iterator<SiteMapURL> sitemapitr = sitemap.getSiteMapUrls().iterator();
        while (sitemapitr.hasNext())
        {
            SiteMapURL url = (SiteMapURL) sitemapitr.next();
            urlsfromSitemap.add(url.getUrl() + "");
            System.out.println(" url " + url.getUrl());
        }`

**Comment by sebastian-nagel** [comment]
Running the sitemap parser from command line works fine:
```
% java -cp ... crawlercommons.sitemaps.SiteMapTester https://help.zoho.com/portal/sitemaps/sitemap-Articles-4001524317312.xml
19/07/25 16:19:14 INFO sitemaps.SiteMapTester:64 - Parsing https://help.zoho.com/portal/sitemaps/sitemap-Articles-4001524317312.xml 
19/07/25 16:19:14 INFO sitemaps.SiteMapTester:93 - https://help.zoho.com/portal/kb/articles/manage-job
19/07/25 16:19:14 INFO sitemaps.SiteMapTester:93 - https://help.zoho.com/portal/kb/articles/overview-of-jobs
```
The tester uses a non-strict SiteMapParser. A strict parser ignores `https://help.zoho.com/portal/...` because it does not have the same prefix as the sitemap (`https://help.zoho.com/portal/sitemaps/`),  please see the [sitemap spec](https://www.sitemaps.org/protocol.html#location) for more details.

**Comment by sebastian-nagel** [comment]
To get a non-strict SiteMapParser, just call the constructor as `new SiteMapParser(false)`.

**Comment by saiprashanth24** [comment]
thank you so much..It works fine .
