### ISSUE TITLE
Normalizing the Percent character

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#263]
The percent character doesn't get normalized (in some cases?)

I think it should be normalized to be %25 instead of %

Example:
`https://www.last.fm/music/Prefuse+73/_/90%+of+My+Mind+Is+With+You`

Is normalized by the chrome browser to:
`https://www.last.fm/music/Prefuse+73/_/90%25+of+My+Mind+Is+With+You`

But our normalizer doesn't change the URL at all

When running Java's URI Normalizer:
`normalizedURL = uri.normalize()`

I get the following stacktrace:
`java.net.URISyntaxException: Malformed escape pair at index 41: https://www.last.fm/music/Prefuse+73/_/90%+of+My+Mind+Is+With+You
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.scanEscape(URI.java:2978)
	at java.net.URI$Parser.scan(URI.java:3001)
	at java.net.URI$Parser.checkChars(URI.java:3019)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)`

**Comment by sebastian-nagel** [comment]
Good catch. Actually, this has been already fixed in Nutch's [BasicURLNormalizer](/apache/nutch/blob/master/src/plugin/urlnormalizer-basic/src/java/org/apache/nutch/net/urlnormalizer/basic/BasicURLNormalizer.java) (crawler-commons' one is a fork of). I'll open a PR to push all improvements into crawler-commons.

**Comment by sebastian-nagel** [comment]
```
> echo "https://www.last.fm/music/Prefuse+73/_/90%+of+My+Mind+Is+With+You" \
    | bin/nutch normalizerchecker  -normalizer urlnormalizer-basic -stdin
Checking combination of these URLNormalizers: BasicURLNormalizer 
https://www.last.fm/music/Prefuse+73/_/90%25+of+My+Mind+Is+With+You
```
