### ISSUE TITLE
Upgrade the toString() method of the BaseRobotRules

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#264]
Currently there is a nice toString in [BaseRobotsRule](https://github.com/crawler-commons/crawler-commons/blob/1c74fc6ca057b02401d41319ba10f90df9c96f0b/src/main/java/crawlercommons/robots/BaseRobotRules.java#L118) method which shows the robots file nicely.

But the toString shows only the first sitemap URL instead of showing all of them.
I understand that this is a calculated decision and not a bug, but as there should not be too many sitemaps in the robots file and if a site has many sitemap it usually will use a sitemap index rather than put all of them in the robots file, so I don't think it will cause any harm if all sitemaps will show in the robots toString.

So if I have a go from the team I will be happy to submit a pull request upgrading the robots toString.

**Comment by Chaiavi** [comment]
Currently the toString looks like this:

> class crawlercommons.robots.SimpleRobotRules:
> no crawl delay
> number of sitemap URLs: 2
>  sitemaps[0]: http://qoutes.over-blog.org/sitemap-news.xml
> number of rules: 4
>Disallow: /mail/subscribe
>Disallow: /mail/valid-*
>Disallow: /contact
>Allow: /

**Comment by sebastian-nagel** [comment]
There should be some limit on the number of sitemaps logged. I've seen robots.txt files ([one example](https://index.commoncrawl.org/CC-MAIN-2018-17/20180426070957/http://livingmoving.com/robots.txt)) listing ten thousands of sitemaps. Calling toString() without any limit eg. for logging may have bad effects. Of course, it's ok to log 10-20 sitemaps and than add a message "remaining N sitemaps skipped" or similar.

**Comment by Chaiavi** [comment]
agreed
