### ISSUE TITLE
How to crawl URL and convert it to Sitemap

### ISSUE THREAD

**Issue by ClearSeve** [crawler-commons/crawler-commons#277]
How to crawl URL and convert it to Sitemap

**Comment by Chaiavi** [comment]
This functionality is not supported by crawler-commons.

You should look for a way to crawl your needed URLs ([crawler4j is a simple option](https://github.com/yasserg/crawler4j))

Then take the list of urls you just crawled and create a sitemap from them, doing a quick search I found the following projects (didn't check them out personally):
[SitemapGen4j](https://github.com/dfabulich/sitemapgen4j)
[JSitemapGenerator](https://github.com/jirkapinkas/jsitemapgenerator)


Good luck.

**Comment by ClearSeve** [comment]
Thank you
