### ISSUE TITLE
NewsAttribute.equals() compares the instance variable PublicationDate with itself.

### ISSUE THREAD

**Issue by evanhalley** [crawler-commons/crawler-commons#289]
NewsAttribute.equals compares the instance variable, PublicationDate, with itself.

See: https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/sitemaps/extension/NewsAttributes.java#L152

It should be compared against the `that.publicationDate`.

**Comment by sebastian-nagel** [comment]
+1 good catch!

**Comment by jnioche** [comment]
Hi @evanhalley, any chance you could open a PR for this?

**Comment by evanhalley** [comment]
@jnioche yep, I am working on it now

**Comment by jnioche** [comment]
Fixed in #291
