### ISSUE TITLE
EffectiveTldFinder: upgrade public suffix list

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#295]
The public suffix list packed with crawler-commons 1.1 dates to March 2019, it should be upgraded, ideally shortly before the release of 1.2. See #219 (40531ef).

**Comment by Chaiavi** [comment]
Is it possible to download it automatically as part of the build process or the release script?

**Comment by rzo1** [comment]
Maybe we can use the **maven-download-plugin** to fetch the latest version from https://publicsuffix.org/list/effective_tld_names.dat during **generate-resources** maven phase?

Shall I provide a PR for it? :)
