### ISSUE TITLE
[sitemaps] Allow to normalize URLs in sitemaps

### ISSUE THREAD

**Issue by murderinc** [crawler-commons/crawler-commons#305]
Url strings  without protocol will produce MalformedURLException. Add protocol to url string if it missing and not strict mode.
Example: http://www.clasohlson.com/sitemap.xml

```
private void maybeAddSiteMap() {
        if (loc == null) {
            return;
        }
        String locUrlString = stripAllBlank(loc);
        //url string without protocol will produce MalformedURLException 
        if (!isStrict()) { //maybe add new flag that user can specify if we should auto assign protocol 
            if (!locUrlString.isEmpty() && !locUrlString.contains("://")) { // simple check if we have "://" in string, or maybe regex that handles ALL protocols what is hard [http, https, ftp, ssl...]
                locUrlString = sitemap.getUrl().getProtocol() + "://" + locUrlString; // get protocol from the sitemap
            }
        }
        try {
            // check that the value is a valid URL
            URL locURL = new URL(locUrlString);
            SiteMap s = new SiteMap(locURL, lastMod);
            sitemap.addSitemap(s);
            LOG.debug("  {}. {}", (i + 1), s);
        } catch (MalformedURLException e) {
            LOG.trace("Don't create an entry with a bad URL", e);
            LOG.debug("Bad url: [{}]", loc);
        }
        loc = null;
        locClosed = false;
        lastMod = null;
    }
```

```
private void maybeAddSiteMapUrl() {
        if (valid) {
            if (loc == null) {
                LOG.debug("Missing url");
                LOG.trace("Can't create an entry with a missing URL");
            } else {
                //no need to check if we should assign protocol, already checked with "valid" flag
                String locUrlString = stripAllBlank(loc.toString());
                if (!locUrlString.isEmpty() && !locUrlString.contains("://")) {
                    locUrlString = sitemap.getUrl().getProtocol() + "://" + locUrlString;
                }
                SiteMapURL sUrl = new SiteMapURL(locUrlString, lastMod, null, null, valid);
                sitemap.addSiteMapUrl(sUrl);
                LOG.debug("  {}. {}", (++i), sUrl);
            }
        }
        loc = null;
        lastMod = null;
    }
```

Duplicate: https://github.com/crawler-commons/crawler-commons/issues/271

**Comment by sebastian-nagel** [comment]
Hi @murderinc, thanks for the issue report and the draft how to solve it. Some comments:

```java
if (!isStrict()) { //maybe add new flag that user can specify if we should auto assign protocol
```
Yes, better add a new option/flag - `strict` has the semantic not to exclude links that do not follow the requirement that the sitemap and the URLs it contains share the same host and path prefix (see [sitemap location](https://www.sitemaps.org/protocol.html#location)). This requirement makes sense for web crawlers and web search engines, other sitemaps would be a cheap way to "inject" tons of spam links into crawlers.

About the example you shared:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <loc>www.clasohlson.com/sitemap/sitemap_product_se.xml</loc>
   </sitemap>
```
First, the [sitemaps spec](https://www.sitemaps.org/protocol.html#locdef) requires fully specified URLs including the scheme. Second, there's some ambiguity with a relative URL which would resolve to `http://base.domain/www.clasohlson.com/..`. Unlikely for this example, but take as counter-example: `mypath/sitemap.xml`.

> Duplicate: #271
Yes same problem, but it's about the URL normalizer not sitemap parsing.

What about extending the SiteMapParser to give users the possibility to plug-in a URL normalizer. E.g.:
```java
    /* Function to normalize or filter URLs. Does nothing by default. */
    private Function<String, String> urlFilter = (String url) -> url;

    /** Set URL filter function */
    public void setURLFilter(Function<String, String> filter) {
        urlFilter = filter;
    }

    /** Use {@link URLFilter} to filter URLs */
    public void setURLFilter(URLFilter filter) {
        urlFilter = filter::filter;
    }
```
The function must be then applied when URLs are added. In case #271 is addressed it would be sufficient to enable its usage by
```java
saxParser.setURLFilter(new BasicURLNormalizer());
```
@murderinc, let us know whether this would be an option?

**Comment by murderinc** [comment]
Hello @sebastian-nagel ,
yes, the filter function much better and more flexible! 
This is what I actually was looking from the very beginning since it is also will give possibility to have custom decoding for urls.
