### ISSUE TITLE
[BasicNormalizer] Provide builder to configure the normalizer

### ISSUE THREAD

**Issue by sebastian-nagel** [crawler-commons/crawler-commons#321]
(suggested by @aecio in [#309](https://github.com/crawler-commons/crawler-commons/pull/309#discussion_r691340841))

With #246/#309 the class BasicURLNormalizer adds a normalization routine which is not safe in rare cases. It should be possible to enable this optimization on-demand only by providing a builder. This would also allow to configure other options (eg. the set of query params to be removed) and to keep the interface clean otherwise (no constructors to pass configurations in).

**Comment by sebastian-nagel** [comment]
Also whether [internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) (IDNs) are converted to ASCII/Punycode (done currently) or Unicode could be made configurable.

**Comment by aecio** [comment]
@sebastian-nagel Let me know if you have started working on this. If you didn't, I can submit a PR for this tomorrow.

**Comment by sebastian-nagel** [comment]
@aecio: not yet, feel free to start. Thanks!

**Comment by aecio** [comment]
@sebastian-nagel done. I haven't added the ability to convert to IDNs to Unicode yet, as it seems a bit trickier (besides converting non-ASCII to Unicode, I think we would also need to detect Punycode and convert it to Unicode?).
I only added the ability to disable IDN normalization, but feel free to implement the Unicode normalization or remove this configuration if you feel it is not really useful.
