### ISSUE TITLE
Support Image Sitemap's

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crawler-commons/crawler-commons#36]
```
Google's documentation on SiteMap support highlights some anomalies with 
regards to the above SiteMap type.
We should consider supporting such functionality.

https://support.google.com/webmasters/answer/178636?hl=en&ref_topic=4581190


```

Original issue reported on code.google.com by `lewis.mc...@gmail.com` on 11 Apr 2014 at 7:21

**Comment by jnioche** [comment]
More generally this is about how to handle extensions of the basic sitemap protocol. Google seem to have developed a whole range of them for news etc...  A source of inspiration could be how ROME  [http://rometools.github.io/rome/] deals with extensions of the feeds, see ForeignMarkup in  [https://github.com/rometools/rome/blob/master/src/main/java/com/rometools/rome/feed/WireFeed.java#L234]

**Comment by kkrugler** [comment]
Rome handles this by returning a list of DOM elements (actual JDOM2 elements), so that it's able to handle pretty much anything that could be found as "extras". If we did the same, we'd be coercing whatever additional data we found in a sitemap into a DOM structure...does that seem OK?
