### ISSUE TITLE
Dependency towards Servlet API

### ISSUE THREAD

**Issue by rzo1** [crawler-commons/crawler-commons#368]
We have a provided dependency towards
```

		<!-- Provided dependencies -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>${servlet-api.version}</version>
			<scope>provided</scope>
		</dependency>
```

which is only used on the `SimpleRobotRulesParserTest` for http status constants:

-     int SC_MOVED_PERMANENTLY = 301;
-     int SC_SERVICE_UNAVAILABLE = 503;
-     int SC_OK = 200;

We have two options:

- (a) Drop the dependency and replace the constants by some custom static constants for t he unit test
- (b) Move it to `test` scope instead of `provided`. 

Any thoughts?

**Comment by jnioche** [comment]
I'd be in favour of doing (a).

**Comment by sebastian-nagel** [comment]
Good catch! Both are good solutions, but if it's only about three int constants, (a) is simpler.

**Comment by rzo1** [comment]
I am also fine using constants from the JDK :) - but we don't need a dependency for just three constants , imho 😬

**Comment by rzo1** [comment]
Fixed with https://github.com/crawler-commons/crawler-commons/commit/73552f0433e663eb8a785cabb4541834c3164e96
