### ISSUE TITLE
Provide a mechanism for users to specify their own handling of non-standard extensions

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#486]
The number of extensions we support for sitemaps is limited to the standard ones.
Google[ recommend](https://developers.google.com/search/docs/specialty/international/localized-versions#sitemap) the use of `rel=”alternate” hreflang=”x”` for specifying the language of a page linked in a sitemap.

Perhaps we could add a mechanism whereby users could specify the name of a class extending ExtensionHandler?

**Comment by sebastian-nagel** [comment]
> use of rel=”alternate” hreflang=”x” for specifying the language of a page linked in a sitemap

This is already implemented, see #149 and [extension.LinkAttributes](https://crawler-commons.github.io/crawler-commons/1.4/crawlercommons/sitemaps/extension/LinkAttributes.html) and [sax.extension.LinksHandler](https://crawler-commons.github.io/crawler-commons/1.4/crawlercommons/sitemaps/sax/extension/LinksHandler.html).

> Perhaps we could add a mechanism whereby users could specify the name of a class extending ExtensionHandler?

The user would also have to implement the a class extending Extension which holds the data extracted by the custom handler. Not an easy undertaking for an user from aside to make them work together.

It wouldn't be a trivial change: the extensions are registered in the enum `Extension` and the extension namespaces are all constants. A dynamic extension registry would need some restructuring.

**Comment by jnioche** [comment]
Closing as already implemented
