### ISSUE TITLE
Proper code styling template and mechanism to enforce it

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crawler-commons/crawler-commons#49]
```
Ken has committed in the past an Eclipse formatting file:
http://code.google.com/p/crawler-commons/source/browse/trunk/doc/eclipse-formatt
er.properties

We should have a generic styling file which will match all IDEs (I personally 
use IntelliJ Idea for example).

If the styling template is accepted by us we should use it, or we can compare 
it to other styling files used by other groups and upgrade it if we see fit.


We should also find a mechanism which will use this file in Maven at the 
"Compile" task automatically.

Possible candidate will be:
http://code.google.com/p/maven-java-formatter-plugin/




Summary:
* Find suitable styling guidelines
* Enforce it using a generic (xml ?) file
* Find a good maven plugin which will run it every compile
```

Original issue reported on code.google.com by `avrah...@gmail.com` on 9 Aug 2014 at 6:58

**Comment by jnioche** [comment]
Use [http://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle.html] plugin?

**Comment by jnioche** [comment]
of for IntelliJ users [https://plugins.jetbrains.com/plugin/6546]

**Comment by jnioche** [comment]
[http://mblanchette.github.io/maven-java-formatter-plugin/0.4/usage.html] looks good but requires a XML formatting file, like the one we had prior to [https://github.com/crawler-commons/crawler-commons/commit/761c9fa64869663d17cf7f79da8d622dc0d9d69e]. 

This would allow us to apply the formatting with Maven. I'll have a look and see if I can get it to work
