### ISSUE TITLE
[url] EffectiveTldFinder - Add a constructor which will auto download the latest TLD list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crawler-commons/crawler-commons#52]
```
Currently, we use our own copy of TLD list.

I suggest adding a constructor which will contain a booleanic flag which will 
indicate the user's wish to download a fresh list from the online server.

Default use of the offline file should be retained.

If the user wishes to download a fresh file but it fails, a fallback to the 
offline file is in place.
```

Original issue reported on code.google.com by `avrah...@gmail.com` on 2 Sep 2014 at 7:53

**Comment by jnioche** [comment]
-1 to this one. Having to handle the download of the file etc... would be a pain. What we could do would be to let the users specify the path to a local custom file via a system property but frankly I'd rather we just updated the version of the file as part of our resources

**Comment by kkrugler** [comment]
-1 from me as well...agree with Julien that supporting file download seems out-of-scope.
