### ISSUE TITLE
[Sitemaps] Upgrade Valid / Legal / Strict SitemapUrls

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crawler-commons/crawler-commons#60]
```
SitemapUrls can be not valid when they are referenced in a sitemap which it's 
directory is on a completely different path than the referenced SitemapUrl.

All as indicated here:
http://www.sitemaps.org/protocol.html#location


In order to clarify the validity aspect we need to upgrade the following
1. Add a little more explanations as javadocs and as logs
2. Rename "Legal" (I think only one occurrence) to "valid" (in the parser)
3. Add to the Sitemap class a new method to get all *valid* SitemapUrls
4. When dropping a URL due to invalidity a log should be shown, a URL shouldn't 
be dropped quietly.
```

Original issue reported on code.google.com by `avrah...@gmail.com` on 9 Nov 2014 at 2:10
* Blocked on: #57

**Comment by jnioche** [comment]
Ok this one seems to be the only one flagged for 0.6

@Chaiavi could you do a Pull Request for it? Don't forget you can apply the formatting with `mvn java-formatter:format` see #76; this will make it a lot easier to review it.

**Comment by Chaiavi** [comment]
ok, will do.

Will take me a couple of days to get to it though...

**Comment by jnioche** [comment]
Removed from 0.6 milestone, we can do this later

**Comment by Chaiavi** [comment]
This one fixes also #90

**Comment by lewismc** [comment]
Can we do a pull request with this one?

**Comment by Chaiavi** [comment]
The pull request exists here:
https://github.com/crawler-commons/crawler-commons/pull/82
