### ISSUE TITLE
[Sitemaps] Parser assumes file encoding is the same as the one used by default on JVM

### ISSUE THREAD

**Issue by GoogleCodeExporter** [crawler-commons/crawler-commons#63]
```
SiteMapParser creates Readers from the byte[] content by assuming that the file 
encoding is the same as the one use by default on the JVM. 

We should use Tika's charset detector (or ICU4J directly) to detect the charset 
used prior to creating the Readers.

Will attach a test class shortly.
```

Original issue reported on code.google.com by `digitalpebble` on 19 Jan 2015 at 4:51

**Comment by sebastian-nagel** [comment]
The attached patch is included in #67 [6eb1459](https://github.com/crawler-commons/crawler-commons/commit/6eb145934581b554e8df2549f09b3720f9c9886a#diff-e0dd11cacc1f2ecf8f25f3402b9b95e4).

**Comment by kkrugler** [comment]
Hi @sebastian-nagel - first, are you saying that this issue can be closed because of the fix for issue #67?

Second, I agree that creating an issue for using StandardCharsets.UTF_8 (now that we're > Java 1.6) is a good idea.

**Comment by sebastian-nagel** [comment]
Afaics, all changes of crawler-commons-63.patch are included in #67 resp. the associated commit. See also #137 which removed further dependencies to system-specific locale.

Ok, I'll open a new issue to use StandardCharsets where applicable (not only UTF-8), and prepare a patch/pr.

**Comment by kkrugler** [comment]
@jnioche - since you originally opened this issue, can you confirm what Sebastian is seeing and then close it if this has been subsumed by #67 and #137? Thanks!

**Comment by jnioche** [comment]
@kkrugler this has been covered elsewhere indeed.
