### ISSUE TITLE
Figure out how to host Javadoc on GitHub

### ISSUE THREAD

**Issue by kkrugler** [crawler-commons/crawler-commons#70]
Typically this is via GitHub Pages - see https://pages.github.com/

So we'd want to create a gh-pages branch, and push the generated Javadoc to that branch.

And we'd need to update the top-level README to link to these Javadocs, versus the (old) version over at Google code

**Comment by Chaiavi** [comment]
Although somewhat old, but I found this link:
http://stackoverflow.com/questions/3939595/making-javadocs-available-with-github-sonatype-maven-repo

**Comment by jnioche** [comment]
I have created a gh-pages branch and pushed the javadoc for the 0.6 release
I will now update the instructions on [https://github.com/crawler-commons/crawler-commons/wiki/Step-by-step-guide-to-generating-a-release] accordingly

**Comment by jnioche** [comment]
The Javadoc is available online on [http://crawler-commons.github.io/crawler-commons/]

**Comment by kkrugler** [comment]
Hi Julien - what's the right URL for Javadoc? I tried http://crawler-commons.github.io/crawler-commons/index.html, but I get a 404, thanks.

**Comment by kkrugler** [comment]
Sorry, just saw your email to the list about the new Javadoc URL - http://crawler-commons.github.io/crawler-commons/0.6/apidocs/
