### ISSUE TITLE
Complete move from Google code

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#73]
I've replaced the references to google code in [2195fb7] we still need to \:
* add a notice to the front page of [https://code.google.com/p/crawler-commons/] telling people that the project has moved
* change our groupID in pom.xml, it is currently `<groupId>com.google.code.crawler-commons</groupId>`. What would be a good value for it? `crawler-commons`?

**Comment by kkrugler** [comment]
Thanks Julien. And crawler-commons seems good to me.

**Comment by Chaiavi** [comment]
+1

**Comment by jnioche** [comment]
Who's the admin on  [https://code.google.com/p/crawler-commons/] ? I don't think I can change the content of the page myself.

**Comment by jnioche** [comment]
Done change of groupID in [master a28a78c]

**Comment by jnioche** [comment]
who has admin rights on [https://code.google.com/p/crawler-commons/]? I can't find how to modify the content of the page there?

**Comment by kkrugler** [comment]
I've got admin rights, and I've made this change. Thanks for following up on this!
