### ISSUE TITLE
simplify pom file

### ISSUE THREAD

**Issue by jnioche** [crawler-commons/crawler-commons#77]
Not clear what was used as a starting point for the pom file but it seems to contain loads of unnecessary things like 

```
<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>${build-helper-maven-plugin.version}</version>
				<executions>
					<execution>
						<id>add-resource</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>add-resource</goal>
						</goals>
						<configuration>
							<resources>
								<resource>
									<directory>src/main/resources</directory>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

which generates a error when importing the project in Eclipse + if I understand correctly simply declares that  `src/main/resources` as a resource, which should be the default in Maven.

The whole point of Maven is to rely on convention over configuration and what we do here seems to be the exact opposite as we are making pretty much everything as explicit as possible.

Any thoughts on this? Can this specific plugin be removed?

**Comment by kkrugler** [comment]
+1 to simplification.

I believe Lewis added this when he Mavenized the build, so hoping he can add some context.

-- Ken

> From: Julien Nioche
> Sent: May 13, 2015 4:35:52am PDT
> To: crawler-commons/crawler-commons
> Subject: [crawler-commons] simplify pom file (#77)
> 
> Not clear what was used as a starting point for the pom file but it seems to contain loads of unnecessary things like
> 
> <plugin>
>                 <groupId>org.codehaus.mojo</groupId>
>                 <artifactId>build-helper-maven-plugin</artifactId>
>                 <version>${build-helper-maven-plugin.version}</version>
>                 <executions>
>                     <execution>
>                         <id>add-resource</id>
>                         <phase>generate-resources</phase>
>                         <goals>
>                             <goal>add-resource</goal>
>                         </goals>
>                         <configuration>
>                             <resources>
>                                 <resource>
>                                     <directory>src/main/resources</directory>
>                                 </resource>
>                             </resources>
>                         </configuration>
>                     </execution>
>                 </executions>
>             </plugin>
> which generates a error when importing the project in Eclipse + if I understand correctly simply declares that src/main/resources as a resource, which should be the default in Maven.
> 
> The whole point of Maven is to rely on convention over configuration and what we do here seems to be the exact opposite as we are making pretty much everything as explicit as possible.
> 
> Any thoughts on this? Can this specific plugin be removed?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------
Ken Krugler
+1 530-210-6378
http://www.scaleunlimited.com
custom big data solutions & training
Hadoop, Cascading, Cassandra & Solr

**Comment by jnioche** [comment]
@lewismc any thoughts on this?

**Comment by lewismc** [comment]
I'll strip all the configuration out just now folks amd submit a PR for this issue.

**Comment by kkrugler** [comment]
@lewismc - I didn't see this referenced in CHANGES.txt

**Comment by lewismc** [comment]
Correct Ken. I used the merge function in the UI and forgot about this. Will update with adhoc commit right now.
