### ISSUE TITLE
[Fetcher] Better port-remove handling 

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#83]
In SimpleHttpFetcher I found this piece of code and comment:

`// HACK - some sites return a redirect with an explicit port number`
`// that's the same as`
`// the default port (e.g. 80 for http), and then when you use this`
`// to make the next`
`// request, the presence of the port in the domain triggers another`
`// redirect, so you`
`// fail with a circular redirect error. Avoid that by converting the`
`// port number to`
`// -1 in that case.`
`//`
`// Detailed scenrio:`
`// http://www.test.com/MyPage ->`
`// http://www.test.com:80/MyRedirectedPage ->`
`// http://www.test.com/MyRedirectedPage`
`// We can save bandwidth:`
`if (result.getScheme().equalsIgnoreCase("http") && (result.getPort() == 80)) {`
`    try {`
`        result = new URI(result.getScheme(), result.getUserInfo(), result.getHost(), -1, result.getPath(), result.getQuery(), result.getFragment());`
`    } catch (URISyntaxException e) {`
`        LOGGER.warn("Unexpected exception removing port from URI", e);`
`    }`
`}`

I suggest using the URLNormalizer to do the work

Related to #74

**Comment by kkrugler** [comment]
I'm going to close this, since we're deprecating SimpleHttpFetcher.
