### ISSUE TITLE
[Fetcher] Return page in case of a non 2xx status code

### ISSUE THREAD

**Issue by Chaiavi** [crawler-commons/crawler-commons#86]
In our SimpleHttpFetcher, we check the status code, and when we encounter a status code not starting with "2" (non 2xx) we throw an Exception:
https://github.com/crawler-commons/crawler-commons/blob/master/src/main/java/crawlercommons/fetcher/http/SimpleHttpFetcher.java#L612

Many times the page itself has html content which we should return to the user instead of throwing an exception.

For example: 404 pages...
Another example: [status code: 500 page] (http://github.io)

Please note that when checking several other http clients - all of them returned the page even when status code was 4xx or 500 (maybe other cases also, I didn't check)

**Comment by kkrugler** [comment]
I'm going to close this, as we'll be deprecating the SimpleHttpFetcher in crawler-commons
