### ISSUE TITLE
[Sitemap] Not able to detect RSS feeds

### ISSUE THREAD

**Issue by yogendrasoni** [crawler-commons/crawler-commons#87]
**Not able to Detect Many RSS feeds**
**Cause:** RSS feeds may have other root tag like `<rdf>` parseSyndicationFormat() method uses `<rss>` tag only.
**Solution:** In place of ``<rss>`` tag, ``<channel >`` tag can be used to detect RSS as a quick fix. 
````
private SiteMap parseSyndicationFormat(URL sitemapUrl, Document doc) throws UnknownFormatException {

        SiteMap sitemap = new SiteMap(sitemapUrl);

        // See if this is an Atom feed by looking for "feed" element
        NodeList list = doc.getElementsByTagName("feed");
        if (list.getLength() > 0) {
            parseAtom(sitemap, (Element) list.item(0), doc);
            sitemap.setProcessed(true);
            return sitemap;
        } else {
            // See if it is a RSS feed by looking for a "rss" element
-             list = doc.getElementsByTagName("rss");
+            list = doc.getElementsByTagName("channel");
            if (list.getLength() > 0) {
                parseRSS(sitemap, doc);
                sitemap.setProcessed(true);
                return sitemap;
            } else {
                throw new UnknownFormatException("Unknown syndication format at " + sitemapUrl);
            }
        }
    }
````

**Comment by kkrugler** [comment]
Do you have an example document that shows this issue? A unit test would be great too, thanks!

**Comment by yogendrasoni** [comment]
I am parsing feed of url 
http://rss.slashdot.org/slashdot/slashdotMain?format=xml

It has format like
````
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" media="screen" href="/~d/styles/rss1full.xsl"?><?xml-stylesheet type="text/css" media="screen" href="http://rss.slashdot.org/~d/styles/itemcontent.css"?>

<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:taxo="http://purl.org/rss/1.0/modules/taxonomy/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:syn="http://purl.org/rss/1.0/modules/syndication/" xmlns:admin="http://webns.net/mvcb/">

<channel rdf:about="http://slashdot.org/">
..
..
````
RSS specification http://web.resource.org/rss/1.0/spec
says that ```<rdf:RDF>``` tag is required outermost tag of RSS1.0.
Syntax:``` <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/">```
Requirement: Required exactly as shown, aside from any additional namespace declarations
Model: (channel, image?, item+, textinput?) 

since RSS 1.x and 2.x both uses ```<channel >``` tag  we can use it for detection of Syndication Format.

I am working on Unit tests. I am searching for other cases and variations in feed formats.

**Comment by yogendrasoni** [comment]
Hello kkruggler,
Sorry for delay in making test case.

here is the link of commit for adding test case.

https://github.com/yogendrasoni/crawler-commons/commit/797f0e1ad87e8bb1dbe188cf6583bcaffd613289

**Comment by kkrugler** [comment]
Hi @yogendrasoni - I've rolled in your fix and test, thanks!
