### ISSUE TITLE
Upgrade javac.src.version and javac.target.version to 1.7 or 1.8

### ISSUE THREAD

**Issue by lewismc** [crawler-commons/crawler-commons#93]
The above is well justified. 1.6 is not supported and neither is 1.7 anymore. We need to think about upgrading javac compliance to at least 1.7.

**Comment by kkrugler** [comment]
+1 for 1.7

**Comment by jnioche** [comment]
+1

**Comment by Chaiavi** [comment]
@lewismc what do you mean by saying that 1.6 is not supported, CC won't run on Java v1.6 or v1.7?

**Comment by lewismc** [comment]
I mean that Oracle do not publish updates to these development kits
anymore.

On Wednesday, September 2, 2015, Avi Hayun <notifications@github.com> wrote:

> @lewismc <https://github.com/lewismc> what do you mean by saying that 1.6
> is not supported, CC won't run on Java v1.6 or v1.7?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crawler-commons/crawler-commons/issues/93#issuecomment-137142457>
> .
>


-- 
*Lewis*

**Comment by Chaiavi** [comment]
Ahh, I see.

Well, we won't have many issues of backwards compatibility as we know most
of the people who are using CC.
But I don't think we should be only java8 compatible, as many people are
still using java7


So I am +1 for java7

**Comment by lewismc** [comment]
Working on this now then folks.
PR coming up.

On Thu, Sep 3, 2015 at 3:48 AM, Avi Hayun <notifications@github.com> wrote:

> Ahh, I see.
>
> Well, we won't have many issues of backwards compatibility as we know most
> of the people who are using CC.
> But I don't think we should be only java8 compatible, as many people are
> still using java7
>
>
> So I am +1 for java7
>
> On Wed, Sep 2, 2015 at 7:02 PM, Lewis John McGibbney <
> notifications@github.com> wrote:
>
> > I mean that Oracle do not publish updates to these development kits
> > anymore.
> >
> > On Wednesday, September 2, 2015, Avi Hayun <notifications@github.com>
> > wrote:
> >
> > > @lewismc <https://github.com/lewismc> what do you mean by saying that
> > 1.6
> > > is not supported, CC won't run on Java v1.6 or v1.7?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/crawler-commons/crawler-commons/issues/93#issuecomment-137142457
> > >
> > > .
> > >
> >
> >
> > --
> > *Lewis*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/crawler-commons/crawler-commons/issues/93#issuecomment-137144647
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crawler-commons/crawler-commons/issues/93#issuecomment-137366503>
> .
>



-- 
*Lewis*

**Comment by jnioche** [comment]
Implemented in #94
