### ISSUE TITLE
Remove HTTP fetcher support

### ISSUE THREAD

**Issue by kkrugler** [crawler-commons/crawler-commons#96]
Once we've let release 0.6 bake for a while, we should remove the deprecated fetcher support.

**Comment by jnioche** [comment]
The next release will be 0.7 and that's where the fetcher classes will be marked as deprecated. We can remove them altogether in 0.8

**Comment by jnioche** [comment]
@kkrugler do you want to take this one or are you happy for me to do it?

**Comment by kkrugler** [comment]
I'll take care of it, thanks.
